### ISSUE TITLE
Page loading stuck at "100"

### ISSUE THREAD

**Issue by Moskoskos** [Moskoskos/TeacherResources#14]
Page stuck at "100" on my dev computer.

**Does not work with:**
Chrome Version 110.0.5481.178 (Official Build) (64-bit)
Versjon 110.0.1587.63 (Offisiell build) (64-biters)

**Does work on**
iOS / Safari: 16.2 in general.
Other people accessing the site.

![image](https://user-images.githubusercontent.com/6773126/223352716-e4b95b0a-fa80-41dd-8bcc-638f7d922399.png)

Chrome Debug Console:

```
moskoskos.atleag.no/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://moskoskos.atleag.no/TeacherResources/_framework/dotnet.7.0.3.opddwkhx2u.js' with computed SHA-256 integrity 'iWGoIcwX1uuc8R9rnXZElmJn8Ma9fotywUlj9muIWR0='. The resource has been blocked.
```

```
Error: Failed to start platform. Reason: TypeError: Failed to fetch dynamically imported module: https://moskoskos.atleag.no/TeacherResources/_framework/dotnet.7.0.3.opddwkhx2u.js
    at Vt (blazor.webassembly.js:1:62194)
(anonymous) @ blazor.webassembly.js:1
```

```
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Comment by thormartin91** [comment]
This seems to be an issue with with integrity check between assets downloaded by the browser and the checksum in `blazor.boot.json`, due to Git changing the line endings in JavaScript files before comitting them to the gh-pages-branch, hence their hash will not match that of `blazor.boot.json`.

Try adding `*.js binary` to a `.gitattributes`-file to treat js-files as binary. 

[Resolve integrity check failures](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures-2)

> When Blazor WebAssembly downloads an app's startup files, it instructs the browser to perform integrity checks on the responses. Blazor sends SHA-256 hash values for DLL (.dll), WebAssembly (.wasm), and other files in the blazor.boot.json file, which isn't cached on clients. The file hashes of cached files are compared to the hashes in the blazor.boot.json file. For cached files with a matching hash, Blazor uses the cached files. Otherwise, files are requested from the server. After a file is downloaded, its hash is checked again for integrity validation. An error is generated by the browser if any downloaded file's integrity check fails.

[Hosting on github pages](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#github-pages-2)

> Git treats JavaScript (JS) files, such as blazor.webassembly.js, as text and converts line endings from CRLF (carriage return-line feed) to LF (line feed) in the deployment pipeline. These changes to JS files produce different file hashes than Blazor sends to the client in the blazor.boot.json file. The mismatches result in integrity check failures on the client. One approach to solving this problem is to add a .gitattributes file with *.js binary line before adding the app's assets to the Git branch. The *.js binary line configures Git to treat JS files as binary files, which avoids processing the files in the deployment pipeline. The file hashes of the unprocessed files match the entries in the blazor.boot.json file, and client-side integrity checks pass.

**Comment by Moskoskos** [comment]
No clue why, but the bug disappeared.
